name: Deploy multi-architecture Docker images with buildx

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags: '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        id: prepare
        run: |
          IMAGE=simonrupf/amavis
          QEMU_PLATFORMS=linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64
          VERSION=${GITHUB_REF##*/}
          echo "buildx_args=--tag ${IMAGE}:latest \
            --tag ${IMAGE}:${VERSION} \
            --platform linux/amd64,linux/386,${QEMU_PLATFORMS} ." >> $GITHUB_OUTPUT
          echo "qemu_platforms=${QEMU_PLATFORMS}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ steps.prepare.outputs.qemu_platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        run: |
          docker buildx build --no-cache --pull --output "type=image,push=false" --build-arg VERSION=${{ steps.prepare.outputs.version }} ${{ steps.prepare.outputs.buildx_args }}
      - name: Docker Login
        if: success() && github.event_name != 'pull_request' && github.ref != 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        if: success() && github.event_name != 'pull_request' && github.ref != 'refs/heads/master'
        run: |
          docker buildx build --output "type=image,push=true" --build-arg VERSION=${{ steps.prepare.outputs.version }} ${{ steps.prepare.outputs.buildx_args }}
      - name: Cleanup
        if: always() && github.event_name != 'pull_request' && github.ref != 'refs/heads/master'
        run: |
          rm -f ${HOME}/.docker/config.json
